In [47]:
import numpy as np

In [48]:
zero_arr = np.zeros(shape=(3,4), dtype="int64")
zero_arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [49]:
zero_arr.dtype

dtype('int64')

In [50]:
ones_arr = np.ones(shape=(2,4))
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
ones_arr.dtype

dtype('float64')

In [52]:
ones_arr.itemsize

8

In [53]:
ones_arr = np.ones(shape=(2,4), dtype="int8")
ones_arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [54]:
ones_arr.dtype

dtype('int8')

In [55]:
ones_arr.itemsize

1

In [56]:
arr = np.array(
    [
        [5,1,7],
        [2,4,6],
        [8,10,16]
    ]
)

arr

array([[ 5,  1,  7],
       [ 2,  4,  6],
       [ 8, 10, 16]])

In [57]:
arr.ndim

2

In [58]:
arr.shape

(3, 3)

In [59]:
flat_array = arr.flatten()

In [60]:
arr

array([[ 5,  1,  7],
       [ 2,  4,  6],
       [ 8, 10, 16]])

In [61]:
flat_array

array([ 5,  1,  7,  2,  4,  6,  8, 10, 16])

In [62]:
flat_array[2] =1000
flat_array

array([   5,    1, 1000,    2,    4,    6,    8,   10,   16])

In [63]:
arr

array([[ 5,  1,  7],
       [ 2,  4,  6],
       [ 8, 10, 16]])

In [64]:
new_flat_array = np.ravel(arr)

In [65]:
new_flat_array

array([ 5,  1,  7,  2,  4,  6,  8, 10, 16])

In [66]:
arr

array([[ 5,  1,  7],
       [ 2,  4,  6],
       [ 8, 10, 16]])

In [67]:
new_flat_array[2] = -50

In [68]:
new_flat_array

array([  5,   1, -50,   2,   4,   6,   8,  10,  16])

In [69]:
arr

array([[  5,   1, -50],
       [  2,   4,   6],
       [  8,  10,  16]])

In [70]:
arr.max()

np.int64(16)

In [71]:
arr.min()

np.int64(-50)

In [72]:
arr.max(axis=-1)

array([ 5,  6, 16])

In [73]:
arr.max(axis=0)

array([ 8, 10, 16])

In [74]:
arr.min(axis=0)

array([  2,   1, -50])

In [75]:
arr.max(axis=None)

np.int64(16)

In [77]:
arr

array([[  5,   1, -50],
       [  2,   4,   6],
       [  8,  10,  16]])

In [78]:
arr.sum()

np.int64(2)

In [80]:
arr.sum(-1)

array([-44,  12,  34])

In [81]:
arr.sum(0)

array([ 15,  15, -28])