<h1 style="color:blue; text-align:center; ">Matrix Operations</h1>

<img src="numpy_matrix.png"></img>

In [1]:
import numpy as np

In [2]:
units_sold_2024 = np.array(
    [
        [5,8,3],
        [10,3,15],
        [15,20,4]
    ]
)

units_sold_2024

array([[ 5,  8,  3],
       [10,  3, 15],
       [15, 20,  4]])

In [3]:
units_sold_2025 = np.array(
    [
        [10,5,4],
        [25,1,40],
        [5,11,1]
    ]
)

units_sold_2025

array([[10,  5,  4],
       [25,  1, 40],
       [ 5, 11,  1]])

<h2>Total Number of unit sold in 2024 and 2025</h2>

In [4]:
units_sold_2024 + units_sold_2025

array([[15, 13,  7],
       [35,  4, 55],
       [20, 31,  5]])

<h2>Sales unit growth from 2024 to 2025</h2>

In [5]:
units_sold_2025 - units_sold_2024

array([[  5,  -3,   1],
       [ 15,  -2,  25],
       [-10,  -9,  -3]])

<h2>Percentage Growth in Sales from 2024 to 2025</h2>

In [6]:
((units_sold_2025 - units_sold_2024)/units_sold_2024)*100

array([[100.        , -37.5       ,  33.33333333],
       [150.        , -66.66666667, 166.66666667],
       [-66.66666667, -45.        , -75.        ]])