<h1 style="color:red; text-align:center">Basic Operations Of Numpy</h1>

In [11]:
import numpy as np

In [12]:
arr = np.array([5,1,7,9,3])
print(arr)
print(arr.dtype)
print(f"Size of one element of numpy array is {arr[0].nbytes} bytes")
print(f"Total size of array = {arr.nbytes} bytes")
print(f"Total elements of array = {arr.size}")
print(f"Dimension of array {arr.ndim}")
print(f"Shape of array = {arr.shape}")

[5 1 7 9 3]
int64
Size of one element of numpy array is 8 bytes
Total size of array = 40 bytes
Total elements of array = 5
Dimension of array 1
Shape of array = (5,)


In [13]:
arr = np.array(
    [
        [2,10,-6],
        [60,10,50],
        [100,250,600],
        [-12,-6,-5]
    ]
)
print(arr)
print(arr.dtype)
print(f"Size of one row of numpy array is {arr[0].nbytes} bytes")
print(f"Size of one element/column of numpy array is {arr[0,0].nbytes} bytes")
print(f"Total size of array = {arr.nbytes} bytes")
print(f"Total elements of array = {arr.size}")
print(f"Dimension of array {arr.ndim}")
print(f"Shape of array = {arr.shape}")

[[  2  10  -6]
 [ 60  10  50]
 [100 250 600]
 [-12  -6  -5]]
int64
Size of one row of numpy array is 24 bytes
Size of one element/column of numpy array is 8 bytes
Total size of array = 96 bytes
Total elements of array = 12
Dimension of array 2
Shape of array = (4, 3)


In [14]:
arr.reshape(6,2)

array([[  2,  10],
       [ -6,  60],
       [ 10,  50],
       [100, 250],
       [600, -12],
       [ -6,  -5]])

In [15]:
arr

array([[  2,  10,  -6],
       [ 60,  10,  50],
       [100, 250, 600],
       [-12,  -6,  -5]])

In [16]:
arr

array([[  2,  10,  -6],
       [ 60,  10,  50],
       [100, 250, 600],
       [-12,  -6,  -5]])

In [17]:
np.sort(arr)

array([[ -6,   2,  10],
       [ 10,  50,  60],
       [100, 250, 600],
       [-12,  -6,  -5]])

In [18]:
arr

array([[  2,  10,  -6],
       [ 60,  10,  50],
       [100, 250, 600],
       [-12,  -6,  -5]])

In [21]:
np.sort(arr,axis=0)

array([[-12,  -6,  -6],
       [  2,  10,  -5],
       [ 60,  10,  50],
       [100, 250, 600]])

In [22]:
np.sort(arr, axis=None)

array([-12,  -6,  -6,  -5,   2,  10,  10,  50,  60, 100, 250, 600])

In [24]:
np.sort(a = arr,kind='stablesort')

array([[ -6,   2,  10],
       [ 10,  50,  60],
       [100, 250, 600],
       [-12,  -6,  -5]])

In [ ]:
np.sort(a = arr)

array([[ -6,   2,  10],
       [ 10,  50,  60],
       [100, 250, 600],
       [-12,  -6,  -5]])