<h1 style="color:blue; text-align:center; ">Matrix Operations</h1>

<img src="numpy_matrix.png"></img>

In [1]:
import numpy as np

In [2]:
units_sold_2024 = np.array(
    [
        [5,8,3],
        [10,3,15],
        [15,20,4]
    ]
)

units_sold_2024

array([[ 5,  8,  3],
       [10,  3, 15],
       [15, 20,  4]])

In [3]:
units_sold_2025 = np.array(
    [
        [10,5,4],
        [25,1,40],
        [5,11,1]
    ]
)

units_sold_2025

array([[10,  5,  4],
       [25,  1, 40],
       [ 5, 11,  1]])

<h2>Total Number of unit sold in 2024 and 2025</h2>

In [4]:
units_sold_2024 + units_sold_2025

array([[15, 13,  7],
       [35,  4, 55],
       [20, 31,  5]])

<h2>Sales unit growth from 2024 to 2025</h2>

In [5]:
units_sold_2025 - units_sold_2024

array([[  5,  -3,   1],
       [ 15,  -2,  25],
       [-10,  -9,  -3]])

<h2>Percentage Growth in Sales from 2024 to 2025</h2>

In [6]:
((units_sold_2025 - units_sold_2024)/units_sold_2024)*100

array([[100.        , -37.5       ,  33.33333333],
       [150.        , -66.66666667, 166.66666667],
       [-66.66666667, -45.        , -75.        ]])

<h2>Prices of Each Product</h2>

In [7]:
prices = np.array(
    [
        [160,100,85],
        [100,86,70],
        [60,50,55]
    ]
)

prices

array([[160, 100,  85],
       [100,  86,  70],
       [ 60,  50,  55]])

<h2>Revenue of products in 2024</h2>

In [8]:
revenue_2024 = units_sold_2024 * prices
revenue_2024

array([[ 800,  800,  255],
       [1000,  258, 1050],
       [ 900, 1000,  220]])

<h2>Discount 25% on prices</h2>

In [9]:
discount = revenue_2024 * 0.25
discount

array([[200.  , 200.  ,  63.75],
       [250.  ,  64.5 , 262.5 ],
       [225.  , 250.  ,  55.  ]])

In [10]:
net_revenue_2024 = revenue_2024 - discount

net_revenue_2024

array([[600.  , 600.  , 191.25],
       [750.  , 193.5 , 787.5 ],
       [675.  , 750.  , 165.  ]])