<h1 style="color:blue; text-align:center; ">Matrix Operations</h1>

<img src="numpy_matrix.png"></img>

In [1]:
import numpy as np

In [2]:
units_sold_2024 = np.array(
    [
        [5,8,3],
        [10,3,15],
        [15,20,4]
    ]
)

units_sold_2024

array([[ 5,  8,  3],
       [10,  3, 15],
       [15, 20,  4]])

In [3]:
units_sold_2025 = np.array(
    [
        [10,5,4],
        [25,1,40],
        [5,11,1]
    ]
)

units_sold_2025

array([[10,  5,  4],
       [25,  1, 40],
       [ 5, 11,  1]])

<h2>Total Number of unit sold in 2024 and 2025</h2>

In [4]:
units_sold_2024 + units_sold_2025

array([[15, 13,  7],
       [35,  4, 55],
       [20, 31,  5]])

<h2>Sales unit growth from 2024 to 2025</h2>

In [5]:
units_sold_2025 - units_sold_2024

array([[  5,  -3,   1],
       [ 15,  -2,  25],
       [-10,  -9,  -3]])

<h2>Percentage Growth in Sales from 2024 to 2025</h2>

In [6]:
((units_sold_2025 - units_sold_2024)/units_sold_2024)*100

array([[100.        , -37.5       ,  33.33333333],
       [150.        , -66.66666667, 166.66666667],
       [-66.66666667, -45.        , -75.        ]])

<h2>Prices of Each Product</h2>

In [7]:
prices = np.array(
    [
        [160,100,85],
        [100,86,70],
        [60,50,55]
    ]
)

prices

array([[160, 100,  85],
       [100,  86,  70],
       [ 60,  50,  55]])

<h2>Revenue of products in 2024</h2>

In [8]:
revenue_2024 = units_sold_2024 * prices
revenue_2024

array([[ 800,  800,  255],
       [1000,  258, 1050],
       [ 900, 1000,  220]])

<h2>Discount 25% on prices</h2>

In [9]:
discount = revenue_2024 * 0.25
discount

array([[200.  , 200.  ,  63.75],
       [250.  ,  64.5 , 262.5 ],
       [225.  , 250.  ,  55.  ]])

In [10]:
net_revenue_2024 = revenue_2024 - discount

net_revenue_2024

array([[600.  , 600.  , 191.25],
       [750.  , 193.5 , 787.5 ],
       [675.  , 750.  , 165.  ]])

<h1>Slicing Of Numpy Arrays</h1>

In [13]:
arr = np.array(
[
    ["","India","China","USA"],
    ["Fold 4",5,10,3],
    ["Iphone 14",15,10,25],
    ["Oneplus 14",25,30,15]
])
arr

array([['', 'India', 'China', 'USA'],
       ['Fold 4', '5', '10', '3'],
       ['Iphone 14', '15', '10', '25'],
       ['Oneplus 14', '25', '30', '15']], dtype='<U21')

In [14]:
arr

array([['', 'India', 'China', 'USA'],
       ['Fold 4', '5', '10', '3'],
       ['Iphone 14', '15', '10', '25'],
       ['Oneplus 14', '25', '30', '15']], dtype='<U21')

In [15]:
arr[1:]

array([['Fold 4', '5', '10', '3'],
       ['Iphone 14', '15', '10', '25'],
       ['Oneplus 14', '25', '30', '15']], dtype='<U21')

In [16]:
arr[1,2]

np.str_('10')

In [17]:
arr[1:,1:]

array([['5', '10', '3'],
       ['15', '10', '25'],
       ['25', '30', '15']], dtype='<U21')

In [18]:
product = arr[1:,1:]
product

array([['5', '10', '3'],
       ['15', '10', '25'],
       ['25', '30', '15']], dtype='<U21')

In [19]:
product.dtype

dtype('<U21')

In [21]:
product = product.astype("int64")

product

array([[ 5, 10,  3],
       [15, 10, 25],
       [25, 30, 15]])

In [22]:
product.dtype

dtype('int64')

In [23]:
product[2][1]

np.int64(30)

In [24]:
students = np.array(
    [
        [101,"Shruti Shinde","Female"],
        [102,"Gaurav Vashisht","Male"],
        [105,"Pranjali Sharma","Female"]
    ]
)
students

array([['101', 'Shruti Shinde', 'Female'],
       ['102', 'Gaurav Vashisht', 'Male'],
       ['105', 'Pranjali Sharma', 'Female']], dtype='<U21')

In [30]:
marks = np.array(
    [
        ['101',50,30,60],
        ['102',65,80,90],
        ['105',10,15,20],

    ]
)
marks

array([['101', '50', '30', '60'],
       ['102', '65', '80', '90'],
       ['105', '10', '15', '20']], dtype='<U21')

In [31]:
combine = np.hstack((students, marks))
combine

array([['101', 'Shruti Shinde', 'Female', '101', '50', '30', '60'],
       ['102', 'Gaurav Vashisht', 'Male', '102', '65', '80', '90'],
       ['105', 'Pranjali Sharma', 'Female', '105', '10', '15', '20']],
      dtype='<U21')